version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: 'lab-mysql'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secure
      - MYSQL_DATABASE=lab_mysql
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: